library(NLP);library(tm);

deletewords1 = c("paulin","bad","sand","seraphin","thierry","mylen",
 "tom","seren","bouchra","camille","camilla",
 "shar","share","jul","jules","enzo","tony","freddy",
 "marjori","helen","sylvain","sylvie")
deletewords2 = c(
 "aillagon","ains","ais","alain","alex","alexanda", 
 "alexandr","alli","and","angel","anne","antoin", 
 "appartenabt","aurel","aut","aven","bah","ball", 
 "baptista","barr","ben","berg","bernard","bours", 
 "bruno","can","cantinant","carl","carr","catherine", 
 "ced","cel","chantal","charlas","chin","christian", 
 "christin","christophe","claud","comprada","condit", 
 "cong","cop","copi","corp","cot","cotis","coul", 
 "cre","cred","dam","dang","daniel","dat","david", 
 "decis","del","dem","den","denf","dep","deputains", 
 "det","detat","detr","dev","deven","dir","dossic", 
 "dun","ellea","eme","enti","ere","eric","eti", 
 "eton","euh","even","fall","fbid","feature","franck",
 "frederic","gar","gen","george","ger","gerard", 
 "guillaume","guy","hein","hel","hop","hor","html", 
 "https","hugo","hui","immensa","impos","ingenie", 
 "isabel","jam","jerome","john","jol","jou","jpg", 
 "julien","kevin","koi","laurence","laurent","len", 
 "lettrai","lev","lilla","log","lon","lor","lou","lun", 
 "mar","marc","marion","martin","medi","mel","mem","men", 
 "michel","mid","milli","min","mour","nai","naim","nant", 
 "nathalia","nont","olivia","opine","org","pal","pap", 
 "para","parf","pascal","patr","patric","patrick","paul", 
 "per","pfff","philipp","pis","pit","pitois","plai","pol", 
 "pos","pourr","pourt","prom","pron","put","qua","quase", 
 "quil","quon","quun","rac","ram","raymond","ref","regimbe", 
 "ren","rep","rest","retable","reusse","rol","romain","sacha", 
 "sam","sant","saur","sci","sebastien","sen","serge","set", 
 "sil","stephan","sub","sura","temp","ten","terr","tet", 
 "thom","traver","tre","tristam","ven","vincent","chi","jeudi"
)

myStopwords <- c(stopwords("french"),
                 "http","www","facebook","com","le","truncated","fwww", 
                 "hashtag",deletewords1,deletewords2)

synonyms <- list(
  list(word="complet", syns=c("complcte","compl")),
  list(word="concret", syns=c("concrcte")),
  list(word="bfm", syns=c("bfmtv")),
  list(word="evenement", syns=c("evcnement")),
  list(word="google", syns=c("goo")),
  list(word="resistance", syns=c("resistaaaaaaaaaaaaaaaaaaanceuuuuuuuuuuh")),
  list(word="euros", syns=c("euro","eures")),
  list(word="fsuivez", syns=c("frsuivez")),
  list(word="evajoly", syns=c("eva","joly")),
  list(word="marinelepen", syns=c("marine","lepen")),
  list(word="jeanlucmelenchon", syns=c("melenchon","melanchon","luc","jean")),
  list(word="nicolassarkozy", 
  syns=c("sarkozy","sarkoz","sarkozysme","sarkozyst","sarkosy","sarko","sarkos")),
  list(word="francoishollande", 
  syns=c("hollande","holland","holand")),
  list(word="francoisbayrou", syns=c("bayrou")),
  list(word="philippepoutou", syns=c("philippe","poutou")),
  list(word="nicolasdupontaignan", syns=c("dupont","aignan")),
  list(word="nicolas", syns=c("nico","nicol")),
  list(word="youtube", syns=c("youtu","youtub")),
  list(word="web", syns=c("webseries","webserie")),
  list(word="africain", sync=c("afriquain")),
  list(word="aim", sync=c("aiment")),
  list(word ="alger", sync=c("algerien")),
  list(word ="aller", sync=c("allait","alle")),
  list(word ="allemagne", sync=c("allemand")),
  list(word ="aller", sync=c("allez")),
  list(word ="ami", sync=c("amis")),
  list(word ="apprendre", sync=c("apprend","apprendr","appris")),
  list(word ="arriver", sync=c("arriv","arrive","arrivent")),
  list(word ="attendre", sync=c("attend","attendent","attendra","attent")),
  list(word ="aujourdhui", sync=c("aujourd")),
  list(word ="batter", sync=c("batt","battra","battu")),
  list(word ="betise", sync=c("bet")),
  list(word ="blanc", sync=c("blanch")),
  list(word ="boire", sync=c("bois","boit")),
  list(word ="budget", sync=c("budgetaire")),
  list(word ="certain", sync=c("cert")),
  list(word ="choix", sync=c("chois")),
  list(word ="combat", sync=c("combattra")),
  list(word ="comprendre", sync=c("compren","comprend","comprendr","comprennent")),
  list(word ="connaitre", sync=c("connaissaez","connaissent","connaitra")),
  list(word ="construir", sync=c("construct","construit")),
  list(word ="continu", sync=c("continuon")),
  list(word ="convaincre", sync=c("convaincra","convaincu")),
  list(word ="coupable", sync=c("couplable")),
  list(word ="credible", sync=c("credibilite")), 
  list(word ="cris", sync=c("cri")),
  list(word ="criminel", sync=c("crim")),
  list(word ="croir", sync=c("croi","croient","crois")),
  list(word ="defendre", sync=c("defend","defendra","defens")),
  list(word ="dernier", sync=c("dernie")),
  list(word ="desole", sync=c("desol")),
  list(word ="detruir", sync=c("detruit")),
  list(word ="deux", sync=c("deuxiem")),
  list(word ="devenir", sync=c("devien","devient")),
  list(word ="devoir", sync=c("devon","devra")),
  list(word ="dictature", sync=c("dictateur")),
  list(word ="difficil", sync=c("difficult")),
  list(word ="dire", sync=c("discuss","disent","dit")),
  list(word ="devoir", sync=c("dois","doit","doivent")),
  list(word ="ecrir", sync=c("ecris","ecrit")),
  list(word ="election", sync=c("electeur","elect","electoral","electorat")),
  list(word ="elire", sync=c("elir","elit","elu","elus")),
  list(word ="emploi", sync=c("emplois","employ")),
  list(word ="enfance", sync=c("enfant")),
  list(word ="entendre", sync=c("entend","entendeur","entendra","entendu")),
  list(word ="espagn", sync=c("espagnol")),
  list(word ="espoir", sync=c("esper","esperon")),
  list(word ="essai", sync=c("essay")),
  list(word ="etre", sync=c("etaient","etais","etait","etant")),
  list(word ="eur", sync=c("euros")),
  list(word ="europe", sync=c("europ","europeen")),
  list(word ="exister", sync=c("exist","existent")),
  list(word ="fair", sync=c("fais","faison","fait")),
  list(word ="famille", sync=c("familial","famill")),
  list(word ="faveur", sync=c("favor","favoris")),
  list(word ="financier", sync=c("financ","financi")),
  list(word ="fiscal", sync=c("fisc")),
  list(word ="fout", sync=c("foutr","foutu")),
  list(word ="gagner", sync=c("gagn","gagnent")),
  list(word ="general", sync=c("gener")),
  list(word ="hain", sync=c("haineux")),
  list(word ="halal", sync=c("hallal")),
  list(word ="histore", sync=c("histoir")),
  list(word ="honte", sync=c("hont","honteux")),
  list(word ="info", sync=c("infos")),
  list(word ="injustice", sync=c("injuste")),
  list(word ="italien", sync=c("itali")),
  list(word ="jour", sync=c("journe")),
  list(word ="laiss", sync=c("laisson")),
  list(word ="language", sync=c("langage","languae")),
  list(word ="lire", sync=c("lir","lis")),
  list(word ="loi", sync=c("lois")),
  list(word ="long", sync=c("longue")),
  list(word ="majorite", sync=c("majorit","majoritaire")),
  list(word ="mauvais", sync=c("mauvai")),
  list(word ="max", sync=c("maximum")),
  list(word ="mechant", sync=c("mechaaant")),
  list(word ="mettre", sync=c("mettent","mettr")),
  list(word ="monde", sync=c("mond","mondial")),
  list(word ="nouveau", sync=c("nouvel")),
  list(word ="null", sync=c("nul")),
  list(word ="oubli", sync=c("oublai")),
  list(word ="ouverture", sync=c("ouvert","ouvri")),
  list(word ="parler", sync=c("parl","parlent","parlon")),
  list(word ="passe", sync=c("pass")),
  list(word ="penser", sync=c("pens","pense","pensent")),
  list(word ="perdre", sync=c("perd","perdr","perdu")),
  list(word ="permettre", sync=c("permet","permettra")),
  list(word ="pouvair", sync=c("peut","peuvent","peux")),
  list(word ="photo", sync=c("photos")),
  list(word ="plaindre", sync=c("plaindr","plaint")),
  list(word ="plaire", sync=c("plais","plait")),
  list(word ="populaire", sync=c("popul")),
  list(word ="pouvoir", sync=c("pouv","pouvons")),
  list(word ="prefere", sync=c("prefer","preferent")),
  list(word ="premier", sync=c("premi")), 
  list(word ="prendre", sync=c("pren","prend","prendr","prennent")),
  list(word ="produit", sync=c("product")),
  list(word ="professeur", sync=c("prof")),
  list(word ="propragande", sync=c("propagand")),
  list(word ="public", sync=c("publc")),
  list(word ="racism", sync=c("racist")),
  list(word ="reconnaitre", sync=c("recon","reconnaissable","reconnaitra","reconnu")),
  list(word ="reduir", sync=c("reduit")),
  list(word ="rejoinder", sync=c("rejoignaient","rejoindra")),
  list(word ="remerci", sync=c("remerc")),
  list(word ="remettre", sync=c("remet","remettr")),
  list(word ="render", sync=c("rend","rendr","rendu")),
  list(word ="repondre", sync=c("repond","repondr","repondu","repons")),
  list(word ="reprendre", sync=c("reprend","reprendr")),
  list(word ="responsabilite", sync=c("responsabe","responsabilit")),
  list(word ="rester", sync=c("restent","reston")),
  list(word ="revenir", sync=c("revenu","revenus","revien","revient")),
  list(word ="savoir", sync=c("sais","sait")),
  list(word ="salaire", sync=c("salair","salare")),
  list(word ="savoir", sync=c("savent","savoir")),
  list(word ="servir", sync=c("sert","serv","service")),
  list(word ="sincerite", sync=c("sincer")),
  list(word ="social", sync=c("socialo","socialos")),
  list(word ="soire", sync=c("soir")),
  list(word ="solidarite", sync=c("solidair")),
  list(word ="souffrance", sync=c("souffrace")),
  list(word ="soutenir", sync=c("soutenon","soutenu","soutien","soutiennent","soutient")),
  list(word ="suivre", sync=c("suit","suiv","suivr")),
  list(word ="sympathisan", sync=c("symp","sympath")),
  list(word ="travail", sync=c("travaill","travaillent")),
  list(word ="vouloir", sync=c("veulent","veut","veux","voul","vouloir","voulon","voulu")),
  list(word ="video", sync=c("videos")),
  list(word ="venir", sync=c("vien","viendra","viennent","vient")),
  list(word ="violence", sync=c("violent")),
  list(word ="vivent", sync=c("vivr")),
  list(word ="voir", sync=c("voi","voient","voir","vois","voit")),
  list(word ="voter", sync=c("vot","votent","voton")),
  list(word ="vrai", sync=c("vrais"))
)